name: Build CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
        
    - name: Use Node.js 12.12
      uses: actions/setup-node@v1
      with:
        node-version: 12.12
        
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      working-directory: ./server
      
    - name: Archive Server
      uses: actions/upload-artifact@v1
      with:
        name: target
        path: server/target
      
    - name: Build UI
      run: |
          npm ci
          npm run build:prod 
      working-directory: ./ui
      
    - name: Archive UI
      uses: actions/upload-artifact@v1
      with:
        name: dist
        path: ui/dist
